name: Deployment
on: push
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Print início
        run: echo "início do deploy"
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.SSH_HOST }}
      - name: Pull
        run: ssh lucasbastos@10.0.100.141 "cd /home/lucasbastos/diretorio2 && /usr/bin/git clone https://github.com/zsurbanismo/projeto1c-zs2.git"
