name: Deployment
on: push
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.SSH_HOST }}
      - name: Pull
        run: ssh lucasbastos@10.0.100.141 "mkdir /home/lucasbastos/diretorio2"
